const moviesData = [
    {
        id: 1,
        title: "TOP GUN MAVERICK",
        director: "Joseph Kosinski",
        starring: "Tom Cruise, Jennifer Connelly",
        poster: "/movies/topgun.png", 
    },
    {
        id: 2,
        title: "JERRY MAGUIRE",
        director: "Cameron Crowe",
        starring: "Tom Cruise, Renée Zellweger",
        poster: "/movies/jerry.png",
    },
    {
        id: 3,
        title: "INTERSTELLAR",
        director: "Christopher Nolan",
        starring: "Matthew McConaughey, Anne Hathaway",
        poster: "/movies/interstellar.png",
    },
    {
        id: 4,
        title: "LA LA LAND",
        director: "Damien Chazelle",
        starring: "Ryan Gosling, Emma Stone",
        poster: "/movies/lalaland.png",
    },
    {
        id: 5,
        title: "F1",
        director: "Joseph Kosinski",
        starring: "Brad Pitt, Damson Idris",
        poster: "/movies/f1.png",
    },
    {
        id: 6,
        title: "SPIDER-MAN: INTO THE SPIDER-VERSE",
        director: "Bob Persichetti, Peter Ramsey, Rodney Rothman",
        starring: "Shameik Moore, Jake Johnson",
        poster: "/movies/spiderverse.png",
    },
    {
        id: 7,
        title: "DUNE PART TWO",
        director: "Denis Villeneuve",
        starring: "Timothée Chalamet, Zendaya",
        poster: "/movies/dune.png",
    },
    {
        id: 8,
        title: "JOHN WICK",
        director: "Chad Stahelski",
        starring: "Keanu Reeves, Ian McShane",
        poster: "/movies/johnwick.png",
    },
    {
        id: 9,
        title: "MISSION IMPOSSIBLE 7",
        director: "Christopher McQuarrie",
        starring: "Tom Cruise, Hayley Atwell",
        poster: "/movies/mi7.png",
    },
    {
        id: 10,
        title: "THE HANGOVER",
        director: "Todd Phillips",
        starring: "Bradley Cooper, Ed Helms, Zach Galifianakis",
        poster: "/movies/hangover.png",
    },
    {
        id: 11,
        title: "MEET JOE BLACK",
        director: "Martin Brest",
        starring: "Brad Pitt, Anthony Hopkins",
        poster: "/movies/meetjoeblack.png",
    },
    {
        id: 12,
        title: "JERSEY",
        director: "Gowtam Tinnanuri",
        starring: "Nani, Shraddha Srinath",
        poster: "/movies/jersey.png",
    },
    {
        id: 13,
        title: "KHALEEJA",
        director: "Trivikram Srinivas",
        starring: "Mahesh Babu, Anushka Shetty",
        poster: "/movies/khaleja.png",
    },
    {
        id: 14,
        title: "HI NANA",
        director: "Shouryuv",
        starring: "Nani, Mrunal Thakur",
        poster: "/movies/hinana.png",
    },
    {
        id: 15,
        title: "MR PERFECT",
        director: "Dasaradh",
        starring: "Prabhas, Kajal Aggarwal",
        poster: "/movies/mrperfect.png",
    },
    {
        id: 16,
        title: "HELLO",
        director: "Vikram Kumar",
        starring: "Akhil Akkineni, Kalyani Priyadarshan",
        poster: "/movies/hello.png",
    },
    {
        id: 17,
        title: "MAN OF STEEL",
        director: "Zack Snyder",
        starring: "Henry Cavill, Amy Adams",
        poster: "/movies/mos.png",
    },
    {
        id: 18,
        title: "VANILLA SKY",
        director: "Cameron Crowe",
        starring: "Tom Cruise, Penélope Cruz",
        poster: "/movies/vs.png",
    }
];

export default moviesData;